services:
  app:
    image: php:8.3-fpm
    container_name: esp_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - devnet

  web:
    image: nginx:alpine
    container_name: esp_web
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - devnet

  vite:
    image: node:20-alpine
    container_name: esp_vite
    working_dir: /var/www/html
    ports:
      - "5174:5173"
    volumes:
      - ./:/var/www/html
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    networks:
      - devnet

networks:
  devnet:
    driver: bridge